harmonize_austraits_glonaf = function(match_austraits_tnrs, match_glonaf_tnrs) {
  match_austraits_tnrs %>%
    distinct(name_init_austraits        = Name_submitted,
             species_accepted_austraits = Accepted_species) %>%
    inner_join(
      match_glonaf_tnrs %>%
        distinct(name_init_glonaf        = Name_submitted,
                 species_accepted_glonaf = Accepted_species),
      by = c(species_accepted_austraits = "species_accepted_glonaf")) %>%
    filter(species_accepted_austraits != "")
}

make_austraits_try_traits_correspond = function(austraits_try_convert) {
  austraits_try_convert %>%
    filter(!is.na(trait_name)) %>%
    select(aus_trait_name = trait_name,
           try_trait_name = `TRY name`,
           try_trait_id   = `TRY number`) %>%
    # Convert list of traits ids from character to actual list of integers
    mutate(
      try_trait_id = purrr::map(
        try_trait_id, function(trait_id_list) {
          if (!is.na(trait_id_list)) {
            # Split list by non words chararacters
            strsplit(trait_id_list, "\\W+") %>%
              .[[1]] %>%
              as.integer()
          } else {
            NA_integer_
          }
        }
      )
    )
}

make_austraits_bien_traits_correspond = function(
  aus_try_convert_df, bien_try_convert_df) {

  tibble::tribble(
    ~bien_trait_name, ~aus_trait_name,
    "plant flowering duration", "flowering_time",
    "plant fruiting duration",  "fruiting_time"
  )
}

get_austraits_traits_for_glonaf_species = function(
  austraits, harmonized_austraits_glonaf
) {
  austraits[["traits"]] %>%
    distinct(taxon_name, trait_name) %>%
    inner_join(harmonized_austraits_glonaf %>%
                 distinct(name_init_austraits, species_accepted_austraits),
               by = c(taxon_name = "name_init_austraits")) %>%
    distinct(species_accepted_austraits, trait_name) %>%
    arrange(species_accepted_austraits, trait_name) %>%
    filter(species_accepted_austraits != "")
}


count_austraits_species_per_trait = function(aus_traits) {
  aus_traits %>%
    dplyr::count(trait_name, sort = TRUE, name = "n_sp")
}

count_austraits_trait_per_species = function(aus_traits) {
  aus_traits %>%
    dplyr::count(species_accepted_austraits, sort = TRUE, name = "n_traits")
}

get_austraits_trait_combinations = function(aus_traits) {
  aus_traits %>%
    dplyr::group_by(species = species_accepted_austraits) %>%
    dplyr::summarise(trait_names = list(trait_name))
}

get_austraits_top_trait_combinations = function(aus_traits, aus_top_traits) {
  aus_traits %>%
    semi_join(aus_top_traits, by = "trait_name") %>%
    get_austraits_trait_combinations()
}

make_non_try_aus_traits_category = function(consolidated_trait_names) {
  consolidated_trait_names %>%
    filter(
      is.na(bien_trait_name) & !is.na(aus_trait_name)
    ) %>%
    select(aus_trait_name) %>%
    mutate(
      trait_cat = case_when(
        aus_trait_name == 'Jmax_per_area'                         ~ "leaf",
        aus_trait_name == 'N_to_P_ratio'                          ~ "leaf",
        aus_trait_name == 'Vcmax_per_area'                        ~ "leaf",
        aus_trait_name == 'accessory_cost_fraction'               ~ "stem",
        aus_trait_name == 'accessory_cost_mass'                   ~ "stem",
        aus_trait_name == 'bark_Al_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_B_per_dry_mass'                   ~ "stem",
        aus_trait_name == 'bark_C_per_dry_mass'                   ~ "stem",
        aus_trait_name == 'bark_Ca_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_Cu_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_Fe_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_K_per_dry_mass'                   ~ "stem",
        aus_trait_name == 'bark_Mg_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_Mn_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_N_per_dry_mass'                   ~ "stem",
        aus_trait_name == 'bark_Na_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_P_per_dry_mass'                   ~ "stem",
        aus_trait_name == 'bark_S_per_dry_mass'                   ~ "stem",
        aus_trait_name == 'bark_Zn_per_dry_mass'                  ~ "stem",
        aus_trait_name == 'bark_ash_content_per_dry_mass'         ~ "stem",
        aus_trait_name == 'bark_cellulose_per_dry_mass'           ~ "stem",
        aus_trait_name == 'bark_delta13C'                         ~ "stem",
        aus_trait_name == 'bark_delta15N'                         ~ "stem",
        aus_trait_name == 'bark_density'                          ~ "stem",
        aus_trait_name == 'bark_lignin_per_dry_mass'              ~ "stem",
        aus_trait_name == 'bark_mass_area'                        ~ "stem",
        aus_trait_name == 'bark_morphology'                       ~ "stem",
        aus_trait_name == 'bark_tannin_per_dry_mass'              ~ "stem",
        aus_trait_name == 'bark_thickness'                        ~ "stem",
        aus_trait_name == 'bark_water_content_per_dry_mass'       ~ "stem",
        aus_trait_name == 'bark_water_content_per_saturated_mass' ~ "stem",
        aus_trait_name == 'branch_mass_fraction'                  ~ "stem",
        aus_trait_name == 'bulk_modulus_of_elasticity'            ~ "stem",
        aus_trait_name == 'ca'                                    ~ "leaf",
        aus_trait_name == 'calcicole_status'                      ~ "life_history",
        aus_trait_name == 'carotenoid_per_area'                   ~ "leaf",
        aus_trait_name == 'carotenoid_per_dry_mass'               ~ "leaf",
        aus_trait_name == 'cc'                                    ~ "leaf",
        aus_trait_name == 'cell_cross-sectional_area'             ~ "leaf",
        aus_trait_name == 'cell_epidermis_Ca_per_fresh_mass'      ~ "leaf",
        aus_trait_name == 'cell_epidermis_P_per_fresh_mass'       ~ "leaf",
        aus_trait_name == 'cell_hypodermis_Ca_per_fresh_mass'     ~ "leaf",
        aus_trait_name == 'cell_hypodermis_P_per_fresh_mass'      ~ "leaf",
        aus_trait_name == 'cell_internal_parenchyma_Ca_per_fresh_mass' ~ "leaf",
        aus_trait_name == 'cell_internal_parenchyma_P_per_fresh_mass'  ~ "leaf",
        aus_trait_name == 'cell_palisade_mesophyll_Ca_per_fresh_mass'  ~ "leaf",
        aus_trait_name == 'cell_palisade_mesophyll_P_per_fresh_mass'   ~ "leaf",
        aus_trait_name == 'cell_rubisco_N_per_total_N'                 ~ "leaf",
        aus_trait_name == 'cell_rubisco_concentration'                 ~ "leaf",
        aus_trait_name == 'cell_sclerenchyma_Ca_per_fresh_mass'        ~ "leaf",
        aus_trait_name == 'cell_sclerenchyma_P_per_fresh_mass'         ~ "leaf",
        aus_trait_name == 'cell_spongy_mesophyll_Ca_per_fresh_mass'    ~ "leaf",
        aus_trait_name == 'cell_spongy_mesophyll_P_per_fresh_mass'     ~ "leaf",
        aus_trait_name == 'cell_thylakoid_N_per_total_N'    ~ "leaf",
        aus_trait_name == 'chlorophyll_A_B_ratio'           ~ "leaf",
        aus_trait_name == 'chlorophyll_A_per_area'          ~ "leaf",
        aus_trait_name == 'chlorophyll_A_per_dry_mass'      ~ "leaf",
        aus_trait_name == 'chlorophyll_B_per_area' ~ "leaf",
        aus_trait_name == 'chlorophyll_B_per_dry_mass' ~ "leaf",
        aus_trait_name == 'chlorophyll_per_area' ~ "leaf",
        aus_trait_name == 'chlorophyll_per_dry_mass' ~ "leaf",
        aus_trait_name == 'ci_at_Amax' ~ "leaf",
        aus_trait_name == 'ci_at_Asat' ~ "leaf",
        aus_trait_name == 'ci_at_ambient' ~ "leaf",
        aus_trait_name == 'ci_over_ca' ~ "leaf",
        aus_trait_name == 'competitive_stratum' ~ "life_history",
        aus_trait_name == 'cotyledon_function' ~ "leaf",
        aus_trait_name == 'cotyledon_position' ~ "leaf",
        aus_trait_name == 'cotyledon_type' ~ "leaf",
        aus_trait_name == 'dead_wood_Ca_per_dry_mass' ~ "stem",
        aus_trait_name == 'dead_wood_K_per_dry_mass' ~ "stem",
        aus_trait_name == 'dead_wood_Mg_per_dry_mass' ~ "stem",
        aus_trait_name == 'dead_wood_N_per_dry_mass' ~ "stem",
        aus_trait_name == 'dead_wood_Na_per_dry_mass' ~ "stem",
        aus_trait_name == 'dead_wood_P_per_dry_mass' ~ "stem",
        aus_trait_name == 'diaspore_mass' ~ "seed",
        aus_trait_name == 'dispersal_appendage' ~ "flower",
        aus_trait_name == 'dormancy_type' ~ "life_history",
        aus_trait_name == 'embryo_colour' ~ "seed",
        aus_trait_name == 'epidermal_cell_density_abaxial' ~ "leaf",
        aus_trait_name == 'epidermal_cell_density_adaxial' ~ "leaf",
        aus_trait_name == 'epidermal_cell_density_both_sides' ~ "leaf",
        aus_trait_name == 'epidermis_thickness' ~ "leaf",
        aus_trait_name == 'epidermis_thickness_lower_leaf_surface' ~ "leaf",
        aus_trait_name == 'epidermis_thickness_upper_leaf_surface' ~ "leaf",
        aus_trait_name == 'establishment_light_environment_index' ~ NA_character_,
        aus_trait_name == 'fire_and_establishing' ~ "life_history",
        aus_trait_name == 'fire_cued_seeding' ~ "life_history",
        aus_trait_name == 'fire_flame_duration' ~ "life_history",
        aus_trait_name == 'fire_fuel_bed_bulk_density' ~ "life_history",
        aus_trait_name == 'fire_fuel_comsumption' ~ "life_history",
        aus_trait_name == 'fire_rate_of_spread' ~ "life_history",
        aus_trait_name == 'fire_response' ~ "life_history",
        aus_trait_name == 'fire_response_detailed' ~ "life_history",
        aus_trait_name == 'fire_response_juvenile' ~ "life_history",
        aus_trait_name == 'fire_response_on_maturity' ~ "life_history",
        aus_trait_name == 'fire_smoulder_duration' ~ "life_history",
        aus_trait_name == 'fire_time_to_ignition' ~ "life_history",
        aus_trait_name == 'fire_total_burn_duration' ~ "life_history",
        aus_trait_name == 'flood_regime_classification' ~ NA_character_,
        aus_trait_name == 'flower_N_per_dry_mass' ~ "flower",
        aus_trait_name == 'flower_androecium_structural_merism' ~ "flower",
        aus_trait_name == 'flower_androecium_structural_phyllotaxis' ~ "flower",
        aus_trait_name == 'flower_androecium_structural_whorls_count' ~ "flower",
        aus_trait_name == 'flower_anther_attachment' ~ "flower",
        aus_trait_name == 'flower_anther_connective_extension' ~ "flower",
        aus_trait_name == 'flower_anther_dehiscence' ~ "flower",
        aus_trait_name == 'flower_anther_orientation' ~ "flower",
        aus_trait_name == 'flower_count_maximum' ~ "flower",
        aus_trait_name == 'flower_fertile_stamens_count' ~ "flower",
        aus_trait_name == 'flower_filament' ~ "flower",
        aus_trait_name == 'flower_filament_fusion' ~ "flower",
        aus_trait_name == 'flower_filament_fusion_to_inner_perianth' ~ "flower",
        aus_trait_name == 'flower_gynoecium_phyllotaxis' ~ "flower",
        aus_trait_name == 'flower_gynoecium_placentation' ~ "flower",
        aus_trait_name == 'flower_ovary_fusion' ~ "flower",
        aus_trait_name == 'flower_ovary_position' ~ "flower",
        aus_trait_name == 'flower_ovules_per_functional_carpel_count' ~ "flower",
        aus_trait_name == 'flower_perianth_differentiation' ~ "flower",
        aus_trait_name == 'flower_perianth_fusion' ~ "flower",
        aus_trait_name == 'flower_perianth_merism' ~ "flower",
        aus_trait_name == 'flower_perianth_parts_count' ~ "flower",
        aus_trait_name == 'flower_perianth_phyllotaxis' ~ "flower",
        aus_trait_name == 'flower_perianth_symmetry' ~ "flower",
        aus_trait_name == 'flower_perianth_whorls_count' ~ "flower",
        aus_trait_name == 'flower_pollen_aperture_shape' ~ "flower",
        aus_trait_name == 'flower_pollen_apertures_count' ~ "flower",
        aus_trait_name == 'flower_structural_carpels_count' ~ "flower",
        aus_trait_name == 'flower_structural_sex_type' ~ "flower",
        aus_trait_name == 'flower_style_differentiation' ~ "flower",
        aus_trait_name == 'flower_style_fusion' ~ "flower",
        aus_trait_name == 'fluorescence_Jmax_over_Vcmax' ~ "leaf",
        aus_trait_name == 'fluorescence_Jmax_per_mass' ~ "leaf",
        aus_trait_name == 'fluorescence_Vcmax_per_mass' ~ "leaf",
        aus_trait_name == 'fruit_Ca_per_dry_mass' ~ "seed",
        aus_trait_name == 'fruit_K_per_dry_mass' ~ "seed",
        aus_trait_name == 'fruit_Mg_per_dry_mass' ~ "seed",
        aus_trait_name == 'fruit_N_per_dry_mass' ~ "seed",
        aus_trait_name == 'fruit_P_per_dry_mass' ~ "seed",
        aus_trait_name == 'fruit_S_per_dry_mass' ~ "seed",
        aus_trait_name == 'fruit_breadth' ~ "seed",
        aus_trait_name == 'fruit_mass' ~ "seed",
        aus_trait_name == 'fruit_wall_width' ~ "seed",
        aus_trait_name == 'fruit_width' ~ "seed",
        aus_trait_name == 'fv_over_fm' ~ "leaf",
        aus_trait_name == 'genome_size' ~ "life_history",
        aus_trait_name == 'germination' ~ "seed",
        aus_trait_name == 'germination_treatment' ~ "seed",
        aus_trait_name == 'glaucous' ~ "leaf",
        aus_trait_name == 'growth_habit' ~ "life_history",
        aus_trait_name == 'guard_cell_length' ~ "leaf",
        aus_trait_name == 'huber_value' ~ "stem",
        aus_trait_name == 'hydraulic_safety_margin_50' ~ "stem",
        aus_trait_name == 'hypocotyl_type' ~ "leaf",
        aus_trait_name == 'insoluable_protein_per_area' ~ "leaf",
        aus_trait_name == 'inundation_tolerance' ~ "life_history",
        aus_trait_name == 'leaf_Al_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_B_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Ca_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Cl_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Co_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Cr_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Cu_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Fe_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_K_per_area' ~ "leaf",
        aus_trait_name == 'leaf_K_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Mg_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Mn_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Mo_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Na_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Ni_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_PRI' ~ "leaf",
        aus_trait_name == 'leaf_S_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Se_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Si_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_Zn_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_absorption' ~ "leaf",
        aus_trait_name == 'leaf_angle' ~ "leaf",
        aus_trait_name == 'leaf_area_ratio' ~ "leaf",
        aus_trait_name == 'leaf_arrangement' ~ "leaf",
        aus_trait_name == 'leaf_ash_content_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_cell_wall_N' ~ "leaf",
        aus_trait_name == 'leaf_cell_wall_N_fraction' ~ "leaf",
        aus_trait_name == 'leaf_cell_wall_fraction' ~ "leaf",
        aus_trait_name == 'leaf_cellulose_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_curliness' ~ "leaf",
        aus_trait_name == 'leaf_dark_respiration_per_area' ~ "leaf",
        aus_trait_name == 'leaf_dark_respiration_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_dark_transpiration_per_area' ~ "leaf",
        aus_trait_name == 'leaf_delta13C' ~ "leaf",
        aus_trait_name == 'leaf_delta15N' ~ "leaf",
        aus_trait_name == 'leaf_delta18O' ~ "leaf",
        aus_trait_name == 'leaf_density' ~ "leaf",
        aus_trait_name == 'leaf_division' ~ "leaf",
        aus_trait_name == 'leaf_fresh_mass_per_area' ~ "leaf",
        aus_trait_name == 'leaf_hairs_adult' ~ "leaf",
        aus_trait_name == 'leaf_hairs_juvenile' ~ "leaf",
        aus_trait_name == 'leaf_hydraulic_conductivity' ~ "leaf",
        aus_trait_name == 'leaf_hydraulic_vulnerability' ~ "leaf",
        aus_trait_name == 'leaf_light_respiration_per_area' ~ "leaf",
        aus_trait_name == 'leaf_lignin_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_margin' ~ "leaf",
        aus_trait_name == 'leaf_mass_fraction' ~ "leaf",
        aus_trait_name == 'leaf_mass_to_stem_mass' ~ "leaf",
        aus_trait_name == 'leaf_mesophyll_conductance_per_area' ~ "leaf",
        aus_trait_name == 'leaf_mesophyll_conductance_per_mass' ~ "leaf",
        aus_trait_name == 'leaf_phenol_content_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_phenology' ~ "leaf",
        aus_trait_name == 'leaf_photosynthetic_nitrogen_use_efficiency_maximum' ~ "leaf",
        aus_trait_name == 'leaf_photosynthetic_nitrogen_use_efficiency_saturated' ~ "leaf",
        aus_trait_name == 'leaf_photosynthetic_phosphorus_use_efficiency_maximum' ~ "leaf",
        aus_trait_name == 'leaf_photosynthetic_phosphorus_use_efficiency_saturated' ~ "leaf",
        aus_trait_name == 'leaf_reflectance' ~ "leaf",
        aus_trait_name == 'leaf_reflectance_near_infrared' ~ "leaf",
        aus_trait_name == 'leaf_relative_water_content_at_turgor_loss_point' ~ "leaf",
        aus_trait_name == 'leaf_relative_water_content_predawn' ~ "leaf",
        aus_trait_name == 'leaf_shape' ~ "leaf",
        aus_trait_name == 'leaf_soluable_starch_per_mass' ~ "leaf",
        aus_trait_name == 'leaf_soluable_sugars_per_mass' ~ "leaf",
        aus_trait_name == 'leaf_specific_conductivity' ~ "leaf",
        aus_trait_name == 'leaf_tannin_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_total_non-structural_carbohydrates_per_area' ~ "leaf",
        aus_trait_name == 'leaf_total_non-structural_carbohydrates_per_mass' ~ "leaf",
        aus_trait_name == 'leaf_transmission' ~ "leaf",
        aus_trait_name == 'leaf_transpiration' ~ "leaf",
        aus_trait_name == 'leaf_transpiration_at_Amax' ~ "leaf",
        aus_trait_name == 'leaf_transpiration_at_Asat' ~ "leaf",
        aus_trait_name == 'leaf_turgor_loss_point' ~ "leaf",
        aus_trait_name == 'leaf_type' ~ "leaf",
        aus_trait_name == 'leaf_water_content_per_area' ~ "leaf",
        aus_trait_name == 'leaf_water_content_per_dry_mass' ~ "leaf",
        aus_trait_name == 'leaf_water_content_per_fresh_mass' ~ "leaf",
        aus_trait_name == 'leaf_water_content_per_saturated_mass' ~ "leaf",
        aus_trait_name == 'leaf_work_to_punch' ~ "leaf",
        aus_trait_name == 'leaf_work_to_punch_adjusted' ~ "leaf",
        aus_trait_name == 'leaf_work_to_shear' ~ "leaf",
        aus_trait_name == 'leaf_work_to_shear_adjusted' ~ "leaf",
        aus_trait_name == 'leaf_work_to_tear' ~ "leaf",
        aus_trait_name == 'leaf_work_to_tear_adjusted' ~ "leaf",
        aus_trait_name == 'leaf_xylem_delta15N' ~ "leaf",
        aus_trait_name == 'life_form' ~ "life_history",
        aus_trait_name == 'lifespan' ~ "life_history",
        aus_trait_name == 'lower_cuticle_thickness' ~ "leaf",
        aus_trait_name == 'lower_hypodermis_thickness' ~ "leaf",
        aus_trait_name == 'lower_palisade_cell_thickness' ~ "leaf",
        aus_trait_name == 'modified_NDVI' ~ "leaf",
        aus_trait_name == 'modulus_of_elasticity_bark' ~  "stem",
        aus_trait_name == 'modulus_of_elasticity_stem' ~  "stem",
        aus_trait_name == 'modulus_of_elasticity_xylem' ~ "stem",
        aus_trait_name == 'modulus_of_rupture' ~ "stem",
        aus_trait_name == 'nitrogen_fixing' ~ "root",
        aus_trait_name == 'osmotic_potential' ~ "leaf",
        aus_trait_name == 'osmotic_potential_at_full_turgor' ~ "leaf",
        aus_trait_name == 'palisade_cell_length' ~ "leaf",
        aus_trait_name == 'palisade_cell_width'  ~ "leaf",
        aus_trait_name == 'palisade_layer_number' ~ "leaf",
        aus_trait_name == 'parasitic' ~ "life_history",
        aus_trait_name == 'pendulous_leaves' ~ "leaf",
        aus_trait_name == 'photosynthetic_bark' ~ "stem",
        aus_trait_name == 'photosynthetic_pathway' ~ "life_history",
        aus_trait_name == 'physical_defence' ~ "leaf",
        aus_trait_name == 'plant_type_by_resource_use' ~ "life_history",
        aus_trait_name == 'plant_width' ~ "height",
        aus_trait_name == 'ploidy' ~ "life_history",
        aus_trait_name == 'regen_strategy' ~ "life_history",
        aus_trait_name == 'reproductive_light_environment_index' ~ NA_character_,
        aus_trait_name == 'reproductive_maturity' ~ "life_history",
        aus_trait_name == 'resorption_leaf_N' ~ "leaf",
        aus_trait_name == 'resorption_leaf_P' ~ "leaf",
        aus_trait_name == 'resprouting_proportion_individuals' ~ "life_history",
        aus_trait_name == 'resprouting_strength' ~ "life_history",
        aus_trait_name == 'root_C_per_dry_mass' ~ "root",
        aus_trait_name == 'root_N_per_dry_mass' ~ "root",
        aus_trait_name == 'root_delta13C' ~ "root",
        aus_trait_name == 'root_delta15N' ~ "root",
        aus_trait_name == 'root_distribution_coefficient' ~ "root",
        aus_trait_name == 'root_dry_matter_content' ~ "root",
        aus_trait_name == 'root_fine_root_coarse_root_ratio' ~ "root",
        aus_trait_name == 'root_mass_fraction' ~ "root",
        aus_trait_name == 'root_morphology' ~ "root",
        aus_trait_name == 'root_shoot_ratio' ~ "root",
        aus_trait_name == 'root_soluable_starch_per_mass' ~ "root",
        aus_trait_name == 'root_soluable_sugars_per_mass' ~ "root",
        aus_trait_name == 'root_structure' ~ "root",
        aus_trait_name == 'root_wood_density' ~ "root",
        aus_trait_name == 'root_xylem_delta15N' ~ "root",
        aus_trait_name == 'salt_tolerance' ~ NA_character_,
        aus_trait_name == 'sapwood_specific_conductivity' ~ "stem",
        aus_trait_name == 'sapwood_specific_conductivity_theoretical' ~ "stem",
        aus_trait_name == 'seed_Ca_concentration' ~ "seed",
        aus_trait_name == 'seed_K_concentration' ~ "seed",
        aus_trait_name == 'seed_Mg_concentration' ~ "seed",
        aus_trait_name == 'seed_N_concentration' ~ "seed",
        aus_trait_name == 'seed_P_concentration' ~ "seed",
        aus_trait_name == 'seed_S_concentration' ~ "seed",
        aus_trait_name == 'seed_breadth' ~ "seed",
        aus_trait_name == 'seed_longevity' ~ "seed",
        aus_trait_name == 'seed_mass_reserve' ~ "seed",
        aus_trait_name == 'seed_oil_content' ~ "seed",
        aus_trait_name == 'seed_protein_content' ~ "seed",
        aus_trait_name == 'seed_release' ~ "seed",
        aus_trait_name == 'seed_shape' ~ "seed",
        aus_trait_name == 'seed_storage_location' ~ "seed",
        aus_trait_name == 'seed_texture' ~ "seed",
        aus_trait_name == 'seed_viability' ~ "seed",
        aus_trait_name == 'seed_volume' ~ "seed",
        aus_trait_name == 'seed_width' ~ "seed",
        aus_trait_name == 'seedling_first_leaf' ~ "leaf",
        aus_trait_name == 'seedling_first_node' ~ "leaf",
        aus_trait_name == 'seedling_germination_location' ~ "seed",
        aus_trait_name == 'senesced_leaf_Al_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_B_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_C_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Ca_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Cu_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Fe_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_K_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Mg_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Mn_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Mo_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_N_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Na_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_P_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_S_per_dry_mass' ~ "leaf",
        aus_trait_name == 'senesced_leaf_Zn_per_dry_mass' ~ "leaf",
        aus_trait_name == 'serotiny' ~ "seed",
        aus_trait_name == 'sex_type' ~ "flower",
        aus_trait_name == 'snow_tolerance' ~ NA_character_,
        aus_trait_name == 'soil_salinity_tolerance' ~ NA_character_,
        aus_trait_name == 'soil_seedbank' ~ "seed",
        aus_trait_name == 'soluable_protein_per_area' ~ "leaf",
        aus_trait_name == 'soluable_starch_per_area' ~ "leaf",
        aus_trait_name == 'soluable_sugars_per_area' ~ "leaf",
        aus_trait_name == 'specific_root_area' ~ "root",
        aus_trait_name == 'specific_root_length' ~ "root",
        aus_trait_name == 'specific_taproot_length' ~ "root",
        aus_trait_name == 'spinescence' ~ "leaf",
        aus_trait_name == 'spongy_mesophyll_thickness' ~ "leaf",
        aus_trait_name == 'sprout_depth' ~ "root",
        aus_trait_name == 'starch_per_area' ~ "leaf",
        aus_trait_name == 'stem_C_per_dry_mass' ~ "stem",
        aus_trait_name == 'stem_N_per_dry_mass' ~ "stem",
        aus_trait_name == 'stem_count_categorical' ~ "stem",
        aus_trait_name == 'stem_density' ~ "stem",
        aus_trait_name == 'stem_dry_matter_content' ~ "stem",
        aus_trait_name == 'stem_hydraulic_conductivity' ~ "stem",
        aus_trait_name == 'stem_mass_fraction' ~ "stem",
        aus_trait_name == 'stem_respiration_per_dry_mass' ~ "stem",
        aus_trait_name == 'stem_soluable_starch_per_mass' ~ "stem",
        aus_trait_name == 'stem_soluable_sugars_per_mass' ~ "stem",
        aus_trait_name == 'stem_water_content_per_saturated_mass' ~ "stem",
        aus_trait_name == 'stem_water_delta18O' ~ "stem",
        aus_trait_name == 'stomatal_density_abaxial' ~ "leaf",
        aus_trait_name == 'stomatal_density_adaxial' ~ "leaf",
        aus_trait_name == 'stomatal_density_average' ~ "leaf",
        aus_trait_name == 'stomatal_distribution' ~ "leaf",
        aus_trait_name == 'stomatal_resistance_conductance_ambient' ~ "leaf",
        aus_trait_name == 'support_fraction' ~ NA_character_,
        aus_trait_name == 'tap_root' ~ "root",
        aus_trait_name == 'thickest_root_diameter' ~ "root",
        aus_trait_name == 'time_from_fire_to_fruit' ~ "life_history",
        aus_trait_name == 'transverse_branch_area_specific_conductivity' ~ "stem",
        aus_trait_name == 'twig_area' ~ "stem",
        aus_trait_name == 'twig_length' ~ "stem",
        aus_trait_name == 'upper_cuticle_thickness' ~ "leaf",
        aus_trait_name == 'upper_hypodermis_thickness' ~ "leaf",
        aus_trait_name == 'upper_palisade_cell_thickness' ~ "leaf",
        aus_trait_name == 'vegetative_regeneration' ~ NA_character_,
        aus_trait_name == 'vein_angle_secondary' ~ "leaf",
        aus_trait_name == 'vein_density' ~ "leaf",
        aus_trait_name == 'vessel_density' ~ "stem",
        aus_trait_name == 'vessel_density_leaves' ~ "leaf",
        aus_trait_name == 'vessel_diameter' ~ "leaf",
        aus_trait_name == 'vessel_diameter_hydraulic' ~ "leaf",
        aus_trait_name == 'vessel_diameter_leaves' ~ "leaf",
        aus_trait_name == 'vessel_lumen_fraction' ~ "leaf",
        aus_trait_name == 'vessel_multiple_fraction' ~ "leaf",
        aus_trait_name == 'vessel_non_lumen_fraction' ~ "leaf",
        aus_trait_name == 'vessel_wall_fraction' ~ "leaf",
        aus_trait_name == 'vine_climbing_mechanism' ~ "stem",
        aus_trait_name == 'water_band_index' ~ "leaf",
        aus_trait_name == 'water_logging_tolerance' ~ NA_character_,
        aus_trait_name == 'water_potential_50percent_lost_conductivity' ~ "stem",
        aus_trait_name == 'water_potential_88percent_lost_conductivity' ~ "stem",
        aus_trait_name == 'water_potential_midday' ~ "leaf",
        aus_trait_name == 'water_potential_predawn' ~ "leaf",
        aus_trait_name == 'water_use_efficiency_integrated' ~ "leaf",
        aus_trait_name == 'water_use_efficiency_intrinsic' ~ "leaf",
        aus_trait_name == 'water_use_efficiency_photosynthetic' ~ "leaf",
        aus_trait_name == 'whole_plant_transpiration' ~ "height",
        aus_trait_name == 'wood_C_per_dry_mass' ~ "stem",
        aus_trait_name == 'wood_Ca_per_dry_mass' ~ "stem",
        aus_trait_name == 'wood_K_per_dry_mass' ~ "stem",
        aus_trait_name == 'wood_Mg_per_dry_mass' ~ "stem",
        aus_trait_name == 'wood_N_per_dry_mass' ~ "stem",
        aus_trait_name == 'wood_Na_per_dry_mass' ~ "stem",
        aus_trait_name == 'wood_P_per_dry_mass' ~ "stem",
        aus_trait_name == 'wood_axial_parenchyma_fraction' ~ "stem",
        aus_trait_name == 'wood_conduit_fraction' ~ "stem",
        aus_trait_name == 'wood_delta13C' ~ "stem",
        aus_trait_name == 'wood_delta15N' ~ "stem",
        aus_trait_name == 'wood_fibre_fraction' ~ "stem",
        aus_trait_name == 'wood_ray_fraction' ~ "stem",
        aus_trait_name == 'wood_tracheid_fraction' ~ "stem",
        TRUE ~ NA_character_
      ))
}
