# Functions to wrangle GIFT trait data specifically

# Outputs a correspondence table between GIFT trait names and TRY IDs
make_gift_try_traits_correspond = function(gift_traits_meta) {
  gift_traits_meta %>%
    mutate(
      trait_ids =
        case_when(
          # Morphological Traits
          Trait2 == "Woodiness_1" ~ list(38),
          Trait2 == "Shoot_length_min" ~ list(NA_real_),
          Trait2 == "Shoot_length_max" ~ list(NA_real_),
          Trait2 == "Growth_form_1" ~ list(NA_real_),
          Trait2 == "Growth_form_2" ~ list(NA_real_),
          Trait2 == "Epiphyte_1" ~ list(NA_real_),
          Trait2 == "Epiphyte_2" ~ list(NA_real_),
          Trait2 == "Climber_1" ~ list(NA_real_),
          Trait2 == "Climber_2" ~ list(NA_real_),
          Trait2 == "Parasite_1" ~ list(NA_real_),
          Trait2 == "Plant_height_min" ~ list(NA_real_),
          Trait2 == "Plant_height_max" ~ list(NA_real_),
          Trait2 == "Plant_height_mean" ~ list(NA_real_),
          Trait2 == "Plant_height_measured" ~ list(NA_real_),
          Trait2 == "Aquatic_1" ~ list(NA_real_),
          Trait2 == "DBH_min" ~ list(NA_real_),
          Trait2 == "DBH_max" ~ list(NA_real_),
          Trait2 == "DBH_mean" ~ list(NA_real_),
          Trait2 == "DBH_measured" ~ list(NA_real_),
          Trait2 == "Shoot_orientation" ~ list(NA_real_),
          # Life-history traits
          Trait2 == "Lifecycle_1" ~ list(NA_real_),
          Trait2 == "Lifespan_1" ~ list(NA_real_),
          Trait2 == "Lifespan_2" ~ list(NA_real_),
          Trait2 == "Life_form_1" ~ list(NA_real_),
          Trait2 == "Life_form_2" ~ list(NA_real_),
          Trait2 == "Deciduousness_1" ~ list(NA_real_),
          # Reproduction traits
          Trait2 == "Self_fertilization_1" ~ list(NA_real_),
          Trait2 == "Seed_length_min" ~ list(NA_real_),
          Trait2 == "Seed_length_max" ~ list(NA_real_),
          Trait2 == "Seed_length_mean" ~ list(NA_real_),
          Trait2 == "Seed_length_measured" ~ list(NA_real_),
          Trait2 == "Seed_width_min" ~ list(NA_real_),
          Trait2 == "Seed_width_max" ~ list(NA_real_),
          Trait2 == "Seed_width_mean" ~ list(NA_real_),
          Trait2 == "Seed_width_measured" ~ list(NA_real_),
          Trait2 == "Seed_height_min" ~ list(NA_real_),
          Trait2 == "Seed_height_max" ~ list(NA_real_),
          Trait2 == "Seed_height_mean" ~ list(NA_real_),
          Trait2 == "Seed_height_measured" ~ list(NA_real_),
          Trait2 == "Fruit_length_min" ~ list(NA_real_),
          Trait2 == "Fruit_length_max" ~ list(NA_real_),
          Trait2 == "Fruit_length_mean" ~ list(NA_real_),
          Trait2 == "Fruit_length_measured" ~ list(NA_real_),
          Trait2 == "Fruit_width_min" ~ list(NA_real_),
          Trait2 == "Fruit_width_max" ~ list(NA_real_),
          Trait2 == "Fruit_width_mean" ~ list(NA_real_),
          Trait2 == "Fruit_width_measured" ~ list(NA_real_),
          Trait2 == "Fruit_height_min" ~ list(NA_real_),
          Trait2 == "Fruit_height_max" ~ list(NA_real_),
          Trait2 == "Fruit_height_mean" ~ list(NA_real_),
          Trait2 == "Fruit_height_measured" ~ list(NA_real_),
          Trait2 == "Fruit_type_1" ~ list(NA_real_),
          Trait2 == "Dehiscence_1" ~ list(NA_real_),
          Trait2 == "Fruit_dryness_1" ~ list(NA_real_),
          Trait2 == "Seed_volume_min" ~ list(NA_real_),
          Trait2 == "Seed_volume_max" ~ list(NA_real_),
          Trait2 == "Seed_volume_mean" ~ list(NA_real_),
          Trait2 == "Seed_volume_measured" ~ list(NA_real_),
          Trait2 == "Seed_mass_min" ~ list(NA_real_),
          Trait2 == "Seed_mass_max" ~ list(NA_real_),
          Trait2 == "Seed_mass_mean" ~ list(NA_real_),
          Trait2 == "Seed_mass_measured" ~ list(NA_real_),
          Trait2 == "Monocarpy" ~ list(NA_real_),
          Trait2 == "Flower_colour" ~ list(NA_real_),
          Trait2 == "Fruit_colour" ~ list(NA_real_),
          Trait2 == "Inflorescence" ~ list(NA_real_),
          Trait2 == "Inflorescence_length_min" ~ list(NA_real_),
          Trait2 == "Inflorescence_length_max" ~ list(NA_real_),
          Trait2 == "Flower_length_min" ~ list(NA_real_),
          Trait2 == "Flower_length_max" ~ list(NA_real_),
          Trait2 == "Flower_width_min" ~ list(NA_real_),
          Trait2 == "Flower_width_max" ~ list(NA_real_),
          Trait2 == "Dispersal_syndrome_1" ~ list(NA_real_),
          Trait2 == "Dispersal_syndrome_2" ~ list(NA_real_),
          Trait2 == "Reproduction_sexual_1" ~ list(NA_real_),
          Trait2 == "Reproduction_asexual_1" ~ list(NA_real_),
          Trait2 == "Reproduction_asexual_2" ~ list(NA_real_),
          Trait2 == "Pollination_syndrome_1" ~ list(NA_real_),
          Trait2 == "Pollination_syndrome_2" ~ list(NA_real_),
          Trait2 == "Pollination_syndrome_3" ~ list(NA_real_),
          Trait2 == "Flowering_start" ~ list(NA_real_),
          Trait2 == "Flowering_end" ~ list(NA_real_),
          Trait2 == "Fruiting_start" ~ list(NA_real_),
          Trait2 == "Fruiting_end" ~ list(NA_real_),
          Trait2 == "Seeds_per_fruit" ~ list(NA_real_),
          # Physiological Traits
          Trait2 == "SLA_min" ~ list(NA_real_),
          Trait2 == "SLA_max" ~ list(NA_real_),
          Trait2 == "SLA_mean" ~ list(NA_real_),
          Trait2 == "SLA_measured" ~ list(NA_real_),
          Trait2 == "Carnivory" ~ list(NA_real_),
          Trait2 == "Leaf_form_1" ~ list(NA_real_),
          Trait2 == "Leaf_margin_1" ~ list(NA_real_),
          Trait2 == "Leaf_spines_1" ~ list(NA_real_),
          Trait2 == "Leaf_thorns_1" ~ list(NA_real_),
          Trait2 == "Leaf_arrangement" ~ list(NA_real_),
          Trait2 == "Succulence" ~ list(NA_real_),
          Trait2 == "Photosynthetic_pathway" ~ list(NA_real_),
          Trait2 == "SSD_min" ~ list(NA_real_),
          Trait2 == "SSD_max" ~ list(NA_real_),
          Trait2 == "SSD_mean" ~ list(NA_real_),
          Trait2 == "SSD_measured" ~ list(NA_real_),
          Trait2 == "Leaf_size_min" ~ list(NA_real_),
          Trait2 == "Leaf_size_max" ~ list(NA_real_),
          Trait2 == "Leaf_size_mean" ~ list(NA_real_),
          Trait2 == "Leaf_size_measured" ~ list(NA_real_),
          Trait2 == "Nitrogen_fix_1" ~ list(NA_real_),
          Trait2 == "Leaf_length_min" ~ list(NA_real_),
          Trait2 == "Leaf_length_max" ~ list(NA_real_),
          Trait2 == "Leaf_length_mean" ~ list(NA_real_),
          Trait2 == "Leaf_length_measured" ~ list(NA_real_),
          Trait2 == "Leaf_width_min" ~ list(NA_real_),
          Trait2 == "Leaf_width_max" ~ list(NA_real_),
          Trait2 == "Leaf_width_mean" ~ list(NA_real_),
          Trait2 == "Leaf_width_measured" ~ list(NA_real_),
          Trait2 == "Leaf_thickness_min" ~ list(NA_real_),
          Trait2 == "Leaf_thickness_max" ~ list(NA_real_),
          Trait2 == "Leaf_thickness_mean" ~ list(NA_real_),
          Trait2 == "Leaf_thickness_measured" ~ list(NA_real_),
          Trait2 == "LDMC_min" ~ list(NA_real_),
          Trait2 == "LDMC_max" ~ list(NA_real_),
          Trait2 == "LDMC_mean" ~ list(NA_real_),
          Trait2 == "LDMC_measured" ~ list(NA_real_),
          # Genetical Traits
          Trait2 == "Chromosome_number" ~ list(NA_real_),
          Trait2 == "Ploidy_level" ~ list(NA_real_),
          # Ecological Traits
          Trait2 == "Elevational_range_min" ~ list(NA_real_),
          Trait2 == "Elevational_range_max" ~ list(NA_real_),
          Trait2 == "Elevational_range_mean" ~ list(NA_real_),
          Trait2 == "Bedrock_1" ~ list(NA_real_),
          Trait2 == "Habitat_1" ~ list(NA_real_),
          Trait2 == "Mycorrhiza_1" ~ list(NA_real_),
          Trait2 == "Mycorrhiza_family" ~ list(NA_real_),
          Trait2 == "Mycorrhiza_species" ~ list(NA_real_),
          Trait2 == "Defense" ~ list(NA_real_),
          TRUE ~ list(NA_real_),
        )
    )
}
